name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Run tests
      run: cargo test --locked

  clippy_check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Run Clippy
      run: cargo clippy --locked --all-targets --all-features
