name: Release

on:
  push:
    tags:
      - '*.*.*'

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      artifact-id: ${{ steps.upload.outputs.artifact-id }}
    steps:
    - name: Check out repository
      uses: actions/checkout@v6

    - name: Build release binary
      env:
        CARGO_TERM_COLOR: always
      run: cargo build --release --locked

    - name: Install nfpm
      run: |
        echo 'deb [trusted=yes] https://repo.goreleaser.com/apt/ /' | sudo tee /etc/apt/sources.list.d/goreleaser.list
        sudo apt update
        sudo apt install -y nfpm

    - name: Create packages
      env:
        VERSION: ${{ github.ref_name }}
      run: |
        nfpm pkg --packager rpm --target target/release
        nfpm pkg --packager deb --target target/release
        nfpm pkg --packager archlinux --target target/release

    - name: Upload release artifacts
      id: upload
      uses: actions/upload-artifact@v7
      with:
        name: bin
        path: |
          target/release/eaw-mod-repack
          target/release/eaw-mod-repack-${{ github.ref_name }}-1.x86_64.rpm
          target/release/eaw-mod-repack_${{ github.ref_name }}_amd64.deb
          target/release/eaw-mod-repack-${{ github.ref_name }}-1-x86_64.pkg.tar.zst

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    needs: build
    steps:
    - name: Check out repository
      uses: actions/checkout@v6

    - name: Download release artifacts
      uses: actions/download-artifact@v8
      with:
        artifact-ids: ${{ needs.build.outputs.artifact-id }}
        path: release

    - name: Create GitHub release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh release create --generate-notes "${{ github.ref_name }}" release/*
